version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "area/dependency"
      - "area/github"
  # Docker
  - package-ecosystem: "docker"
    directory: "/connector/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "area/dependency"
      - "area/docker"
  # Gradle
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "area/dependency"
      - "area/java"
  # NPM
  - package-ecosystem: "npm"
    directory: "/extensions/broker-server-api/client-ts/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 50
    labels:
      - "area/dependency"
      - "area/javascript"
